version: '3'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "<your password>"
    ports:
      - "5432:5432"
    volumes:
      - /home/server/Desktop/postgres/data:/var/lib/postgresql/data 
    networks:
      - postgres_net
      
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "<your email>"
      PGADMIN_DEFAULT_PASSWORD: "<your password>"
    ports:
      - "5558:80"
    networks:
      - postgres_net

networks: 
  postgres_net:
    driver: bridge
